puts "Starting application in #{settings.environment.to_s}"
puts "BUNDLE_GEMFILE => #{ENV['BUNDLE_GEMFILE']}"
puts "GEM_HOME => #{ENV['GEM_HOME']}"
puts "GEM_PATH => #{ENV['GEM_PATH']}"
puts "PATH => #{ENV['PATH']}"
puts "NEO4J_REST_URL => #{ENV['NEO4J_REST_URL']}"
